### ISSUE TITLE
robust spot detection is needed

### ISSUE THREAD

**Issue by mattersoflight** [mehta-lab/multiSero#14]
Segmentation loses quite a few antigen spots and is not robust to smearing of antigen (see #7 for images and segmentations). We need robust method for detecting where antigens are in the array grid. This step is likely time consuming, so making it fast in the next iteration is also good idea.

**Comment by jennyfolkesson** [comment]
@mattersoflight I'm trying out a few things right now starting with opencv blob detection combined with iterative closest point for correspondence. It can be fast if I can get it to work robustly on so few points, we'll see. I'm on limited bandwidth with two kids at home and a bit rusty too, but hopefully I can get a prototype working soon.

**Comment by smguo** [comment]
One solution: 
![image](https://user-images.githubusercontent.com/18110744/77813568-d920c500-7066-11ea-9729-78c7bfb774b6.png)

**Comment by mattersoflight** [comment]
@smguo, just tried your PR (https://github.com/czbiohub/serology-COVID19/pull/16). It runs well on Scienion data, optical densities look usable too. 
<img width="1155" alt="image" src="https://user-images.githubusercontent.com/2934183/77829162-7c142600-70dd-11ea-8266-e64017b5268f.png">

I am copying the results over to googledrive and will be using this output to continue with interpretation notebook. It now uses nd-arrays. You and Janie should continue the analysis (https://github.com/czbiohub/serology-COVID19/blob/master/notebooks_interpretation/20200115_plate4_AEP_Feb3_6mousesera.ipynb).

@bryantChhun and @ieivanov, the interpolation aspect of this PR can help the spot detection methods you are working for octopi data.

**Comment by jennyfolkesson** [comment]
@mattersoflight I have one solution now too. The code is still a bit messy, but you can see it in this notebook:
https://github.com/czbiohub/serology-COVID19/blob/jenny_tests/array_analyzer/extract/spot_detection_icp.ipynb

The spot detection is pretty slow, it takes about 0.6 seconds, but the registration part is faster, about 5 ms. I've only evaluated on the images_octopi/20200325AdamsPlate/Averaged/500us, so I'll have to check robustness on more images.

**Comment by jennyfolkesson** [comment]
![C5_spots](https://user-images.githubusercontent.com/6796901/77863059-72211e80-71d4-11ea-99e2-043255189bc0.jpg)

**Comment by mattersoflight** [comment]
This is great @jennyfolkesson. 

Here are @bryantChhun's notes:
 * wrote a new method “build_block_array” that takes “params” dict returned from “txt_parser.create_xml_dict” and the camera pixel size in mm
* This method creates binary squares, each centered at expected spot position, in an array of row/col specified by the .xml file.
* I have another method “build_and_place_block_array” that will interpolate the A1 position based on regionprops and place this block array there.  This works 100% on the flu data (including H8) if you tune the “select_props”.  Problem is that these hyperparameters don’t work for the octopi data.
* The parameter tuning is getting heavy and may be problematic in the long run.  Some type of fitting would be great, but potentially hard too — Could easily be lots of local minima, so a good loss function should be designed


 I am now doing a comparison and will note my observations here.

**Comment by ieivanov** [comment]
@jennyfolkesson's iterative closest point algorithm works very well for finding the location of fiducial markers only:
https://github.com/czbiohub/serology-COVID19/blob/find_fiduc_fromJenny/array_analyzer/extract/spot_detection_icp.ipynb

Once we have the location of fiducial markers we can easily interpolation the rest of the grid, as already implemented in @bryantChhun's branch. This reduces the requirements on the initial segmentation, making it potentially much faster, and is robust to plates with mostly blank spots (e.g. negative subjects).

Will implement in the repo 

P.S. On a cropped image the SimpleBlobDetector took only 30 ms to find spots.

**Comment by mattersoflight** [comment]
nice work @jennyfolkesson and @ieivanov! The approach works well and is more robust than segmentation. I have added some code to estimate hyper-parameters. If images are scaled to about 1800,  no hyper parameter tuning was required between scienion and octopi data.

Good idea to merge into @bryantChhun's branch.

![image](https://user-images.githubusercontent.com/2934183/77882627-327b2680-7216-11ea-9287-ce8b3707dba5.png)

**Comment by bryantChhun** [comment]
Ok not sure which order we should merge.  I did try integrating jenny's notebook code into the main script but had some hiccups:

- doing a conda install of the latest opencv showed that estimateRigidTransform is not available.  Documentation says it's deprecated and other methods should be used (affine2d), but the outputs are slightly different.  @jennyfolkesson can you check what version of openCV you're using? (mine is 4.2.0)  We can put your version in as a hard requirement.

- there is some pixel scaling to consider.  It looks like Shalin was able to solve this.

and finally, something to keep in mind for later -- Hongquan said that OpenCV needs to be recompiled for Jetson Nano.  A quick google search says this is the case only for versions not deployed on it by default.

**Comment by mattersoflight** [comment]
When you resize image to 1800 and set min spot size set to 500, you do get consistent detection of fiducials. One parameter that is still finicky is spot_distance. It is estimated from histogram of manhattan distance between spots, but it is better to compute it from parameters of the array printer and of the imager.

Data from Octopi:

<img width="747" alt="image" src="https://user-images.githubusercontent.com/2934183/77931970-b9a1bc00-7261-11ea-9433-ca8d5b3afa9f.png">

Data from scienion:
<img width="753" alt="image" src="https://user-images.githubusercontent.com/2934183/77932471-7005a100-7262-11ea-9ffb-dc12457b9a63.png">

**Comment by jennyfolkesson** [comment]
I'm on OpenCV version 3.4.2 - you can tell I've been away for a while. :-)

I will update my code to work with the version the rest of you are using
and move the code into the main repository. I'll send a PR to @Bryant Chhun
<bryant.chhun@czbiohub.org> hopefully by tonight.

**Comment by bryantChhun** [comment]
> I'm on OpenCV version 3.4.2 - you can tell I've been away for a while. :-) I will update my code to work with the version the rest of you are using and move the code into the main repository. I'll send a PR to @bryant Chhun <bryant.chhun@czbiohub.org> hopefully by tonight.


Hi Jenny,
That's actually great.  According to this, OpenCV 3.3.1 is default on jetson nano:

[Link from google search on jetson nano + openCV](https://www.jetsonhacks.com/2019/11/22/opencv-4-cuda-on-jetson-nano/)

Now, it seems if we want cuda acceleration, we may still need to recompile.  Let's hope we're fast enough without it.

**Comment by ieivanov** [comment]
@jennyfolkesson I already incorporated your iterative closest point search in the main repo on the branch find_spot_grid.

I did encounter an issue with this algorithm, however. Take a look at this notebook: https://github.com/czbiohub/serology-COVID19/blob/find_fiduc_fromJenny/array_analyzer/extract/spot_detection_icp.ipynb
When the grid is not initialized close to the target location (i.e. start_x and start_y are off), the algorithm doesn't find the correct target. I'll try a bit to fix that, but if you have time you're welcome to give it a shot as well.

**Comment by jennyfolkesson** [comment]
I'll work on it. ICP is only guaranteed to converge if initialized close
enough to the true solution, so I was expecting that I would have to tune
the initial estimation once I encountered more heterogeneity in the data. @Ivan
Ivanov <ieivanov@stanford.edu> would you mind pointing me the data you
experienced issues with? And why are you using a cropped version of the
image? Thanks!

**Comment by jennyfolkesson** [comment]
Nevermind, I see it's a cropped version of the image in
2020-01-15_plate4_AEP_Feb3_6mousesera...
I will test that folder right now.

**Comment by ieivanov** [comment]
Sure, here is the image. In our pipeline, we pre-crop the well first. This makes the spot segmentation easier, and it also runs much faster.

![H10_crop](https://user-images.githubusercontent.com/11934632/77965896-e4f2ce00-7296-11ea-8f47-eee764e8fc69.png)

**Comment by mattersoflight** [comment]
@ieivanov and @jennyfolkesson , we have occasionally found automatic pre-cropping to be difficult even after this fix (#9 ) and I found cropping after locating fiducials to be more robust.  So we may change our work flow: find fiducials -> crop -> fit grid -> estimate ODs.  

You'll see how cropping worked after fiducials in earlier commit [`improved parameter estimation`](https://github.com/czbiohub/serology-COVID19/blob/3ed1c5ccf61b65fa917e687d85307db56e680efd/array_analyzer/extract/spot_detection_icp.ipynb).

@jennyfolkesson,  as you test, please pull files from two datasets (octopi, scienion). Paths are in above commit. I am inviting you to that google filestream.

Versioning is becoming important - please edit the code that Ivan added to main repo.

On the topic of speed, I was clocking 0.3s for 1800x1800 image for spot detection.

**Comment by smguo** [comment]
I'm testing the master branch with Jenny's approach incorporated but got this error:

A1.png
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py", line 1434, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/syuan-mingguo/python/serology-COVID19/run_array_analyzer.py", line 289, in <module>
    main(sys.argv[1:])
  File "/Users/syuan-mingguo/python/serology-COVID19/run_array_analyzer.py", line 121, in main
    workflow(inputfolder, outputfolder, debug=debug)
  File "/Users/syuan-mingguo/python/serology-COVID19/run_array_analyzer.py", line 208, in workflow
    props_array = assign_props_to_array_2(props_array, props_by_loc)
  File "/Users/syuan-mingguo/python/serology-COVID19/array_analyzer/extract/image_parser.py", line 470, in assign_props_to_array_2
    if arr[key[0], key[1]] and np.mean(value.intensity_image) > np.mean(arr[key[0], key[1]].intensity_image):
IndexError: index 7 is out of bounds for axis 1 with size 6

**Comment by bryantChhun** [comment]
> I'm testing the master branch with Jenny's approach incorporated but got this error:
> 

Can you make a new issue?

**Comment by smguo** [comment]
Sure... just wanted to check if I'm running it right. It errors out on the first image (A1.png)

**Comment by jennyfolkesson** [comment]
I didn't get through all the testing today, toddler refused to nap then continued to have meltdowns the rest of the day... Hopefully the kids will cooperate tomorrow!
It does seem like the pre-cropping of the well is pretty slow, it took several seconds for me. So if I can get the spot detection robust that could speed things up.
Sorry for the newbie question: when you say find fiducials, is that the same as spot detection?

**Comment by mattersoflight** [comment]
No worries Jenny. By fiducials, we mean 5 specific spots that Ivan and I have been registering to the detected spots in above images. These 5 spots are always present in all data. We should probably call them 'reference spots'. Other spots may or may not show up depending on experiment.

**Comment by smguo** [comment]
It took me a while but I was able to make the interpolation approach work for the new Scienion flu plate data:
![H12_overlayCentroids](https://user-images.githubusercontent.com/18110744/78090830-1abfb180-7380-11ea-9bff-aca7bca60bd3.png)
![B7_overlayCentroids](https://user-images.githubusercontent.com/18110744/78090895-46429c00-7380-11ea-951b-902ee0e5d267.png)
![A11_overlayCentroids](https://user-images.githubusercontent.com/18110744/78090935-6c683c00-7380-11ea-95a0-6a6341017aa5.png)
![image](https://user-images.githubusercontent.com/18110744/78090988-8dc92800-7380-11ea-8c1a-bf8c79667ffa.png)

It still fails occasionally on some challenging cases (2-3 wells out of 96 wells), but hopefully combined with the approach @jennyfolkesson @bryantChhun and @ieivanov are developing we can cover almost all the cases. 

The full processed data can be found at 
ELISAarrayReader/images_scienion/2020-03-30-15-08-05-COVD_March25_fluplatetest_AdamsPlate/test_output/3_31_18_7_10

The updated pipeline is in `test_interp_grid` branch. @bryantChhun and I will figure out how to make both methods available in the code base.

**Comment by jennyfolkesson** [comment]
I tested out one idea I had today to initialize the grid, which was to look at intensity profiles in x and y and determine spot locations from there. It worked pretty good, but it was thrown off when there were few spots and very dark dirt near the spots. You can see an example notebook here. http://localhost:8888/notebooks/array_analyzer/extract/icp_initialization.ipynb

It failed on 2 images in the 2020-01-15_plate4_AEP_Feb3_6mousesera dir and 8 (ugh) in the 2020-03-30-15-08-05-COVD_March25_fluplatetest_AdamsPlate dir.

My next plan is to try some type of particle filtering, which hopefully should be able to escape the local minima this first attempt got stuck in.

Sorry this is taking a while, Lex didn't nap again today so things are a bit chaotic...

**Comment by mattersoflight** [comment]
Awesome work @jennyfolkesson, @bryantChhun , and @smguo . The recent tests from merged master look good. I am closing this issue and starting a new one. I think ICP will be very useful in handling edge cases that arise due to experimental factors.
