### ISSUE TITLE
I'm getting this error when running build_and_place_block_array

### ISSUE THREAD

**Issue by jennyfolkesson** [mehta-lab/multiSero#20]
ValueError                                Traceback (most recent call last)
<ipython-input-9-63be6aa886c9> in <module>
----> 1 placed_spotmask = build_and_place_block_array(props_array, spot_mask, params, return_type='region')

~/Code/serology-COVID19/array_analyzer/extract/image_parser.py in build_and_place_block_array(props_array_, spot_mask_, params_, return_type)
    602     target = np.zeros(spot_mask_.shape)
    603     target[int(x_min-temp_origin[0]):int(x_min+template.shape[0]-temp_origin[0]),
--> 604            int(y_min-temp_origin[1]):int(y_min+template.shape[1]-temp_origin[1])] = template
    605 
    606     if return_type == 'product':

ValueError: could not broadcast input array from shape (1248,1672) into shape (714,820)

**Comment by mattersoflight** [comment]
Getting the same error on master. @bryantChhun - would you fix this? After that, I'll enable PR reviews to avoid accidental damage to master.

**Comment by bryantChhun** [comment]
This is related to pixel size.  Ivan's PR #19 fixes this by giving you convenient block to hard code one or the other.

**Comment by bryantChhun** [comment]
Because this is directly related to Issue #31 I am closing this.
