### ISSUE TITLE
Streamline spot detection and OD estimation

### ISSUE THREAD

**Issue by mattersoflight** [mehta-lab/multiSero#23]
We have two major approaches to turn image of array into ODs using `array_analyzer` module. v2 is more robust but in development. v1 is functional for Scienion data. We need to keep processing data from Scienion at rapid clip.

v1:  use segmentation: 
crop well image -> estimate background -> segment spots -> interpolate between centroids of spots to find missing points in the segmentation -> compute spot density and background -> export ODs.

v2: use point detector (https://github.com/czbiohub/serology-COVID19/issues/14): 
fit spots with opencv -> create a reference grid of fiducials using metadata from array printer and imager -> register reference grid to detected spots -> [crop image based on bounding box of the reference grid](https://github.com/czbiohub/serology-COVID19/blob/3ed1c5ccf61b65fa917e687d85307db56e680efd/array_analyzer/extract/spot_detection_icp.ipynb)  -> estimate background -> compute spot density and background -> export ODs.

Until v2 is stable, it is optimal that @bryantChhun  and @jennyfolkesson focus on implementing v2 and test against representative images from Scienion and Octopi, before merging into master. Whereas, @smguo should maintain v1 and process Scienion data. 

Please add your comments on how the pipelines should be changed.

**Comment by smguo** [comment]
I agree. I saw that v1 is missing in the master branch. I'll submit a PR soon to have both v1 & v2 as options that users can choose from. 

I think at this development stage it’s better to have different methods as options in the code base, so we can switch methods easily when one approach fails on certain dataset. Ideally we want a single method that would work for all types of data but it might take a while to figure that out.

**Comment by mattersoflight** [comment]
that's great @smguo, make sure your branch can analyze this data (/Volumes/GoogleDrive/My Drive/ELISAarrayReader/images_scienion/2020-03-30-15-08-05-COVD_March25_fluplatetest_AdamsPlate).

**Comment by mattersoflight** [comment]
@smguo, @bryantChhun  and @jennyfolkesson  will work on v2 on  PR #19.  You can focus on restoring v1 and getting the ODs.

**Comment by mattersoflight** [comment]
The OD estimation with interpolation workflow in the latest master is fairly robust. I suggest integrating useful parts of ICP workflow into interpolation workflow, because ICP workflow does not yet have OD estimation. In the end, we should have single workflow with exception handling.


The interpolation workflow fails on edge cases where experimental artifacts in the images are about the size of the spot. Registration to reference grid with ICP algorithm should overcome this quickly. 

For the problem, see the diagnostic plots for well E5 and similar wells in the data from second fluplate ('/Volumes/GoogleDrive/My Drive/ELISAarrayReader/images_scienion/2020-04-04-14-18-32-COVID_April4_flusecondplate/robinAnalysis20200404_1820`).

Segmentation:
![E5_crop_binary](https://user-images.githubusercontent.com/2934183/78465160-e3fed980-76a6-11ea-8d4e-219bd841670a.png)

Overlay of centroids:
![E5_overlayCentroids](https://user-images.githubusercontent.com/2934183/78465164-e9f4ba80-76a6-11ea-96ba-51b3d8f06fdb.png)

**Comment by mattersoflight** [comment]
Registering the reference grid with ICP does identify spots more accurately in this well:
red x= detected spots, blue + = reference grid, green . = registered grid.
![E5_icp](https://user-images.githubusercontent.com/2934183/78501013-bd748900-770e-11ea-80b7-6e19fe83761c.jpg)

**Comment by mattersoflight** [comment]
But, the background estimation as implemented in `icp_wf.py` is not accurate. 

@bryantChhun , you should integrate the grid registration from icp_wf.py into inter_wf.py. And, create a single workflow out of it.

![E5_crop_bg_overlay](https://user-images.githubusercontent.com/2934183/78502610-d2edb100-7716-11ea-8cde-ccc68eb0e533.png)
![E5_crop](https://user-images.githubusercontent.com/2934183/78502611-d3864780-7716-11ea-9387-36fa1c52aadc.png)
![E5_well_mask](https://user-images.githubusercontent.com/2934183/78502613-d41ede00-7716-11ea-8105-8c6cbb1b46db.png)

**Comment by bryantChhun** [comment]
I believe this issue is also resolved in #34 and #45.  While we still have two potential spot-detection algorithms, the path from robust spot detection to OD calculation is well-integrated.
