### ISSUE TITLE
How to consider pixel size differences

### ISSUE THREAD

**Issue by bryantChhun** [mehta-lab/multiSero#31]
We've been testing against mostly Images acquired on Scienion (camera pixel size = 0.0049 mm).  Octopi has a different camera and different pixel size.  So far we have code that can handle both cameras and code that is pixel-size independent (either approach can be implemented).
We should rationalize which approach is best and focus on one.

Features of pixel-size dependence:
- more robust spot fitting? (not determined)
- more flexibility across camera types, sizes, shapes.

Features of pixel-size independence (scaling all images to common pixel size):
- less required metadata to perform spot fitting
- (against) segmentation parameters could vary with scaled images

**Comment by mattersoflight** [comment]
Analysis steps should be expressed in units of micron and not pixels. Doing so makes it reduces parameter tuning when things like magnification, camera type, or binning change. But, at the same time it makes the parameter tuning clear when the assay format (classical ELISA, scienion array, luminex) change.

**Comment by bryantChhun** [comment]
in PR #57 , we can include camera pixel sizes in the metadata.  The code still uses this to analyze in units of pixels.

**Comment by jennyfolkesson** [comment]
Pixel size is now part of metadata and spot fitting parameters are adjusted accordingly.
