### ISSUE TITLE
Unit testing

### ISSUE THREAD

**Issue by jennyfolkesson** [mehta-lab/multiSero#42]
There's currently no testing of this repo. Since there's quite a few collaborators it would make sense to add unit testing to the code and continuous integrations so we don't accidentally break things as more features are added.

Any preferences on which CI to use? I've used Travis for my previous Biohub projects but would like to try GitHub Actions. https://help.github.com/en/actions

**Comment by bryantChhun** [comment]
> There's currently no testing of this repo. Since there's quite a few collaborators it would make sense to add unit testing to the code and continuous integrations so we don't accidentally break things as more features are added.

I notice you like to use unittest.  Would you prefer we use this over pytest?  I'd be happy to contribute some tests once this is determined and some other simple refactoring is done.

> Any preferences on which CI to use? I've used Travis for my previous Biohub projects but would like to try GitHub Actions. https://help.github.com/en/actions

We had some discussion about using Github Actions on the ReconstructOrder repo.  Syuan-ming looked into this.  I'm on board.

**Comment by jennyfolkesson** [comment]
GitHub Actions has been added for continuous integration, and unit tests are being added to code when deemed helpful for the developer(s).
