### ISSUE TITLE
Add a check on the quality of spot detection and switch to the alternative approach if failed

### ISSUE THREAD

**Issue by smguo** [mehta-lab/multiSero#43]
The failed wells in `fit` workflow seem to complement the failed wells in `interpolation` workflow. This is probably because `fit` approach tries to fit a full grid to the spots, but the fit can fail when only a few spots are present in the image. Interpolation approach on the other hand finds the x,y boundary of the grid and interpolates the grid positions. When fit approach converges to the right answer the determined spot positions seem more accurate than interpolation approach because fit approach fits to all the available spots but interpolation only uses the corner spots. 

I think we can have a check on the quality of spot detection and automatically switch to the alternative approach when detection using one approach fails. Some examples:

Fit approach:
![C3_overlayCentroids](https://user-images.githubusercontent.com/18110744/79025023-784ebd80-7b39-11ea-8cb6-299e1c150e49.png)
![D3_overlayCentroids](https://user-images.githubusercontent.com/18110744/79025049-91576e80-7b39-11ea-97e2-2ee4f8305983.png)
![D1_overlayCentroids](https://user-images.githubusercontent.com/18110744/79025142-ca8fde80-7b39-11ea-8620-cc2e0dcd1af6.png)
![C11_overlayCentroids](https://user-images.githubusercontent.com/18110744/79025164-d7143700-7b39-11ea-9c6a-faf9c9989126.png)

Interpolation approach:
![C3_overlayCentroids](https://user-images.githubusercontent.com/18110744/79025236-02972180-7b3a-11ea-925a-36e778f75aa1.png)
![D3_overlayCentroids](https://user-images.githubusercontent.com/18110744/79025256-0fb41080-7b3a-11ea-992f-2da3ff2c55a5.png)
![D1_overlayCentroids](https://user-images.githubusercontent.com/18110744/79025271-1cd0ff80-7b3a-11ea-9596-a7bfe859dcfe.png)
![C11_overlayCentroids](https://user-images.githubusercontent.com/18110744/79025289-2bb7b200-7b3a-11ea-9f74-0ced2a2be3d6.png)

Fit approach output:
ELISAarrayReader/images_scienion/2020-04-08-14-48-49-COVID_concentrationtest_April8_images/Automated_Analysis_Spot-Fitting/4_10_13_21_19

interpolation approach output (using spot_intensity_fix branch):
ELISAarrayReader/images_scienion/2020-04-08-14-48-49-COVID_concentrationtest_April8_images/Automated_Analysis_Spot-Fitting/4_9_19_25_45

**Comment by mattersoflight** [comment]
Above diagnostic plots are very informative @smguo. Registration (fit) of reference grid works fairly well. Its failure mode is that it cannot find corners when there are only a few spots. You could first register using all spots and then shift the grid by integer intervals to match with the centroids you detect with segmentation of spots.

**Comment by smguo** [comment]
After looking into Jenny's particle filter code, I realized only the 5 fiducials are fitted to the detected spots rather than the whole grid. It seems to me then the issue could be the initial guess of the grids position is off and the optimization got stuck at local minima. The initial position is estimated from average spot positions, and this can be off when only a few spots are present
![C11_registration](https://user-images.githubusercontent.com/18110744/79033984-87e4fb00-7b67-11ea-8349-ac18931f5fa2.jpg)

**Comment by mattersoflight** [comment]
@smguo, @jennyfolkesson - registering a fiducial grid (only 5 blue + points) with detected fiducial spots (only 5 red x points) should be the most robust in principle.

But, detection of just the fiducial spots does not seem to be implemented in registration workflow. Hand-tuned segmentation approach in interpolation workflow does pick up fiducials all the time, but it also picks up other spots.  

So, it is worth combining spot detection of interpolation workflow with grid/fiducial registration of registration workflow.

**Comment by mattersoflight** [comment]
@smguo 
I am noticing another bug with interpolation method - see how point (5,1) and (4,1) end up at the same place:

![A1_overlayCentroids](https://user-images.githubusercontent.com/2934183/79057463-c71e5500-7c16-11ea-9077-775541bfe8e2.png)
![B1_overlayCentroids](https://user-images.githubusercontent.com/2934183/79057465-c980af00-7c16-11ea-83ba-fe582b987fb5.png)

**Comment by jennyfolkesson** [comment]
I agree, I'm satisified with the particle filter performance, but with the new more noisy images I need to switch to a more robust spot detection method. Will work on this tomorrow.

**Comment by smguo** [comment]
I did some troubleshooting. The particle filter works well. The issue is when the blob detecter fails to detect all the 5 fiducials, particle filter won't converge to the correct answer. I tried loosening up the filtering criteria in the blob detector but then other wells failed because of too many detected spots. I ended up adding a Gaussian blur step before the the blob detection and that fixed the issue. The fit approach now works for all wells in COVID data 
C11:
![C11_registration](https://user-images.githubusercontent.com/18110744/79087391-f8b91e00-7cf3-11ea-8965-dad014f4bf6b.jpg)
D1:
![D1_registration](https://user-images.githubusercontent.com/18110744/79087392-f951b480-7cf3-11ea-94b4-e35b00b96c60.jpg)

The output:
/Volumes/GoogleDrive/My Drive/ELISAarrayReader/images_scienion/2020-04-08-14-48-49-COVID_concentrationtest_April8_images/Automated_Analysis_Spot-Fitting/4_12_18_30_38

**Comment by smguo** [comment]
@jennyfolkesson I pushed the changes I made

**Comment by smguo** [comment]
@jennyfolkesson I pushed the changes to branch [spot_intensity_fix_fit](https://github.com/czbiohub/serology-COVID19/tree/spot_intensity_fix_fit). I also made some minor changes to particle filter when I was troubleshooting but those changes shouldn't matter

**Comment by jennyfolkesson** [comment]
Great. I'll create a PR to merge your branch to robustspotdetection. I'll
leave some comments for you. Unfortunately I won't be able to get much work
done today but I'll be working again tomorrow afternoon.

**Comment by jennyfolkesson** [comment]
Dealt with in https://github.com/czbiohub/serology-COVID19/pull/45
