### ISSUE TITLE
Use Pandas dataframe as data structure for holding spot properties  

### ISSUE THREAD

**Issue by smguo** [mehta-lab/multiSero#46]
The pipeline currently use a mix of numpy array, dictionary, and regionprops objects to store/pass the spot properties. It would be nice to switch to pandas dataframe. This will also allow easier integration with the analysis notebook, which uses dataframe as data structure.

**Comment by bryantChhun** [comment]
I made a duplicate issue before seeing this one.  Here are my notes:

**What is the bottleneck? Please describe.**
After some discussion with @smguo, we realized that the "interp" or "fit" spot detection methods depend almost entirely on centroid positions and do not use the np.ndarray format. Additionally, pandas dataframes can read these centroid dictionaries easily, maintaining tabular data for easy reading and reporting.

**Describe the solution you'd like and alternatives**
We can continue to report the array format for intensities, antigens, etc., but this data structure should not be used before or during the spot detection:
- remove several lines that create blank arrays: "txt_parser.create_array"
- adjust "compute_od" to receive dataframes

**Comment by mattersoflight** [comment]
good idea, pandas dataframes make sense, and will make integration with interpretation part of analysis clean.

**Comment by jennyfolkesson** [comment]
Added dataframe for spot properties in https://github.com/czbiohub/pysero/pull/74.
