### ISSUE TITLE
Add check for camera saturation

### ISSUE THREAD

**Issue by ieivanov** [mehta-lab/multiSero#58]
** What is the bottleneck? Please describe.**
Add a check to determine if data are saturated on either end of the intensity range. Saturated intensity will lead to incorrect OD values. Support 8-bit, 12-bit, and 16-bit data types.

**Describe the solution you'd like and alternatives**
Note: Cuttlefish camera does not reach 255 counts, the sensor saturates at ~ 250 counts. Number of pixels at 255 intensity is not a good metric of saturation, maybe check the area of the image reading the same intensity value. You won't get large areas of the same intensity in unsaturated images. Watch out for hot pixels.

On the low end of the range, the data may have an offset, make sure that's dealt with properly.

**Comment by lenafb** [comment]
Closing because this issue is more octopi-specific
