### ISSUE TITLE
background estimator 'underfits' background on negative contrast images

### ISSUE THREAD

**Issue by mattersoflight** [mehta-lab/multiSero#6]
[Background estimation by fitting a surface](https://github.com/czbiohub/serology-COVID19/blob/a00e849cad0a408d44408a0ccd7ba9024a7d138a/array_analyzer/extract/img_processing.py#L125) 'underfits' the background on negative contrast images.

Following is the result of drawing a line profile along horizontal at y=400. This problem is easily solved by inverting the input image.

Image
![image](https://user-images.githubusercontent.com/2934183/77615890-ab644080-6eed-11ea-9088-eb3f5eea6eaf.png)

Profile
![image](https://user-images.githubusercontent.com/2934183/77615916-bd45e380-6eed-11ea-815f-29fc98b72a2e.png)

**Comment by mattersoflight** [comment]
Even after inverting images, the surface fit approach does not report accurate background distribution.

Image
![image](https://user-images.githubusercontent.com/2934183/77616884-026b1500-6ef0-11ea-9860-7c62e45d27ac.png)

Background
![image](https://user-images.githubusercontent.com/2934183/77616903-0b5be680-6ef0-11ea-914c-487dfaecbc95.png)

Line profiles @ y=400
![image](https://user-images.githubusercontent.com/2934183/77616987-3e9e7580-6ef0-11ea-9063-46f2c72e36b2.png)

**Comment by smguo** [comment]
Did you try using higher order function? `get_background` has a `fit_order` parameter for this. I haven't tuned it yet

**Comment by mattersoflight** [comment]
Same issue at higher orders too:

Image
![image](https://user-images.githubusercontent.com/2934183/77620338-67763900-6ef7-11ea-9db5-5d734bd9000e.png)

background with order 3:
![image](https://user-images.githubusercontent.com/2934183/77620488-b623d300-6ef7-11ea-997c-704c3237abb4.png)

![image](https://user-images.githubusercontent.com/2934183/77620597-eec3ac80-6ef7-11ea-9247-d7f56c542710.png)

background with order 4:
![image](https://user-images.githubusercontent.com/2934183/77620461-a4dac680-6ef7-11ea-9d35-5f7487f93bd9.png)

![image](https://user-images.githubusercontent.com/2934183/77620542-d5bafb80-6ef7-11ea-967e-3b7b5a98b10c.png)

**Comment by smguo** [comment]
Looks like the fit is biased by the spots. I'll try robust fit or top-hat to fix this

**Comment by smguo** [comment]
Looks like sampling less pixels from the image for fitting is a quick fix (note the light red shade in the center of the first image but not the second):

Sample with grid size 32
![A1crop_bg_overlay](https://user-images.githubusercontent.com/18110744/77711747-0dc14d80-6f8f-11ea-8ce3-37e0e9c7a46c.png)
![Profiles of A1crop_bg_overlay](https://user-images.githubusercontent.com/18110744/77711767-19147900-6f8f-11ea-8c39-5da9524c542e.jpg)

Sample with grid size 128
![A1crop_bg_overlay](https://user-images.githubusercontent.com/18110744/77711784-2467a480-6f8f-11ea-8dd3-9fa0882a3e11.png)
![Profiles of A1crop_bg_overlay_v2](https://user-images.githubusercontent.com/18110744/77711792-2893c200-6f8f-11ea-83cf-282e0bf55d23.jpg)
