### ISSUE TITLE
Mock Regionprop throws error

### ISSUE THREAD

**Issue by bryantChhun** [mehta-lab/multiSero#62]
**Describe the bug**
See screenshot below.  The bug is caused by mock regionprop's automatic calculation of "mean_intensity", which slices a subregion of the "intensity_image".  Specifically, mock regionprop receives a centroid coordinate that is negative, which causes the errant slicing.

**To Reproduce**
- Run well "B3" from this data: 
/Volumes/GoogleDrive/My Drive/ELISAarrayReader/images_cuttlefish/2020-05-01-17-29-54-COVID_May1_JBassay_images/rotated
- use master branch (5-11-2020)

**Expected behavior**
Error with the screenshot below

**Screenshots**
![image](https://user-images.githubusercontent.com/25647712/81612837-4fb52000-9392-11ea-9d94-b4f32f359680.png)

**Operating environment (please complete the following information):**
 - OS: MacOSX, Master, branch=fishy_registration, branch=enhance_spot_contrast

**Comment by bryantChhun** [comment]
There are many potential solutions to this:
1) we can catch the error at mock regionprop
2) we can catch the error before "get_spot_intensity" is called by catching negative spot coordinates

I prefer option 2 -- it enables us to do some upfront catches to flag poor data.

**Comment by jennyfolkesson** [comment]
Thanks for catching this @bryantChhun , I'll work on it this afternoon.

**Comment by bryantChhun** [comment]
@jennyfolkesson another note.  I think this can happen if the centroid is too close to the edge of the cropped image as well.

This makes me wonder if there's a way we can impose boundaries on the position of the grid.  Or even fancier, some kind of nonlinear loss on the grid positioning such that grids far from center are penalized.

**Comment by jennyfolkesson** [comment]
@bryantChhun There was a bug in how images were cropped which I fixed now, as well as discontinuing the analysis when registration fails. I hope that has solved the problem.
Ideally grid positioning far from the center would be less likely due to less particles there, if the problem persists we can look into tuning the particle x, y standard deviations.

**Comment by bryantChhun** [comment]
This looks fixed in the newest #60 PR.  Will close after we merge.
