### ISSUE TITLE
Rotated arrays generate strange results

### ISSUE THREAD

**Issue by bryantChhun** [mehta-lab/multiSero#64]
**Describe the bug*
When the raw image is rotated, the "_composite_spots_img" debug image rotates the wrong way, appearing to give different results.
When the raw image is aligned properly, the same pipeline gives an accurate "_composite_spots_img".

A3, May1 JVassay images RAW:
![A3_registration](https://user-images.githubusercontent.com/25647712/82365088-0897e200-99c5-11ea-861c-33924328d179.png)
![A3_composite_spots_img](https://user-images.githubusercontent.com/25647712/82365105-0df52c80-99c5-11ea-9fd4-7fe7287609be.png)

A3, May1 JVassay images ALIGNED:
![A3_registration](https://user-images.githubusercontent.com/25647712/82365193-30874580-99c5-11ea-9d22-d02306d09579.png)
![A3_composite_spots_img](https://user-images.githubusercontent.com/25647712/82365181-29f8ce00-99c5-11ea-818c-9ba4d798d6bb.png)

We also see from the green dots that the registration works fine.

**To Reproduce**
Run the data on this data:
(RAW)
/Volumes/GoogleDrive/My Drive/ELISAarrayReader/images_cuttlefish/2020-05-01-17-29-54-COVID_May1_JBassay_images/0deg_named

or this data:
(ALIGNED)
/Volumes/GoogleDrive/My Drive/ELISAarrayReader/images_cuttlefish/2020-05-01-17-29-54-COVID_May1_JBassay_images/rotated

**Expected behavior**
While we normally process on Aligned data, the concern is that slight variations can give dramatically different results.

**Screenshots**

**Operating environment (please complete the following information):**
 - OS: macosx

**Comment by bryantChhun** [comment]
This is a problem with "save_composite_image" which slices into the target array in [row, col] order.  It should slice in [col, row] order.

Fixed in PR #66

**Comment by smguo** [comment]
This could be a bug in get_spot_intensity... the bboxs from mock regionprop and the scikit regionprop rotate in opposite ways in the image... I can look into this

**Comment by bryantChhun** [comment]
problem was indexing, but probably somewhere else.
Fixed in PR #68
