### ISSUE TITLE
New version of xlrd does not support xlsx files

### ISSUE THREAD

**Issue by smguo** [mehta-lab/multiSero#81]
**Describe the bug**
Running pysero with xlrd version > 1.2 will result an error because:

"xlrd has explicitly removed support for anything other than xls files.
This is due to potential security vulnerabilities relating to the use of xlrd version 1.2 or earlier for reading .xlsx files."

See this post for more details:
https://stackoverflow.com/questions/65250207/pandas-cannot-open-an-excel-xlsx-file

A better solution might be switching to openpyxl for xlsx reading, or save all the xlsx files as xls, rather than freezing the xlrd version.

**Comment by lenafb** [comment]
By removing xlrd from the environment, pandas by default uses openpyxl. I will make sure that the update-requirements branch addresses this.
