### ISSUE TITLE
Limit to how many antigen spots pysero can simultaneously analyze

### ISSUE THREAD

**Issue by lenafb** [mehta-lab/multiSero#82]
I receive this error message when attempting to run analysis on plates from an RVP vs VLP vs NS1 comparison:

"ValueError: Internal work array size computation failed: -5 python-BaseException". 

This is an error from scipy.linalg.lapack . At the time of the error, df_fit is a dataframe of shape (23400, 13)

**To Reproduce**

-a
-i
"/Volumes/GoogleDrive/Shared drives/compmicro/ELISAarrayReader/images_nautilus/head2head/pysero_head2head_20210818_0959"
-o
"/Volumes/GoogleDrive/Shared drives/compmicro/ELISAarrayReader/images_nautilus/head2head/pysero_head2head_20210818_0959"
-m
"pysero_analysis_config.xlsx"

**Expected behavior**
fit__mean plot that plots all 13 antigens as subplots with hue according to serum ID

**Operating environment (please complete the following information):**
 - OS: Mac
 - Versions of python packages:
 - scipy 1.7

**Comment by smguo** [comment]
@lenafb Looks like the issue is caused by the metadata? Can you post what changes fixed the issue? and we can close this issue.

**Comment by lenafb** [comment]
This issue was caused by incorporating missing data in the metadata (ie: a column for mAbs when there were no mAbs detected leading to NaN values). This issue is resolved by removing the mAbs in the metadata  in the 
- serum ID
- serum type 
- serum cat
- secondary dilution
- serum dilution
- secondary ID
sheets so that pysero would not analyze data from the failed portion of the experiment.
