### ISSUE TITLE
multisero.py from CLI cannot find input directories, runs fine in pycharm

### ISSUE THREAD

**Issue by jrbyrum13** [mehta-lab/multiSero#92]
When running multisero from the command line on the multisero_refactor branch, the traceback I get is: `Traceback (most recent call last):
  File "multisero.py", line 185, in <module>
    run_multisero(args)
  File "multisero.py", line 141, in run_multisero
    raise ValueError("input directory is not a directory or doesn't exist")`

**To Reproduce**
1. In Terminal, run:
python multisero.py -e -i  ‘input path’ -o ‘output path’ -d -m multisero_output_data_metadata.xlsx
2. Observe traceback
3. In PyCharm, point to the script path and create a config with the same parameters:
"-e
-i
"/Users/janie.byrum/Desktop/cov_folder/png"
-o
"/Users/janie.byrum/Desktop/cov_folder/png7"
-d
-m
multisero_output_data_metadata.xlsx"
4. Observe that multisero runs and extracts ODs

**Additional context**
@lenafb suggested this may be related: https://stackoverflow.com/questions/3761473/python-not-recognising-directories-os-path-isdir

**Comment by lenafb** [comment]
Closing this issue due to path-specific nature and metadata flag elaboration specified in `issues-readme-org` branch
